### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by xunyuan-nuaa** [JoinAI-Inc/simulaix#1]
**Question**
Add your question here

AttributeError: module 'simulaix' has no attribute 'Generator'

**Expected behavior**
If what happened was unexpected, outline the expected behaviour.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]

**Additional context**

**Comment by xxg1413** [comment]
> **Question** Add your question here
> 
> AttributeError: module 'simulaix' has no attribute 'Generator'
> 
> **Expected behavior** If what happened was unexpected, outline the expected behaviour.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. Ubuntu]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

Sorry, our project has not been officially released yet, you need to wait.
